services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    container_name: wordpress_wp # Ce nom sera utilisé par le Nginx reverse proxy
    ports:
      - ${IP}:${PORT}:80 # change ip if required
    volumes:
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    networks:
      - wordpressnet # Réseau interne à l'application WordPress
      - gleyze_network # Réseau partagé avec le Nginx reverse proxy

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
      - wp
    networks:
      - wordpressnet # wpcli reste uniquement sur le réseau interne

  pma:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    container_name: wordpress_pma # Ce nom sera utilisé par le Nginx reverse proxy
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - ${IP}:${PMA_PORT}:80
    volumes:
     - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - wordpressnet # Réseau interne à l'application WordPress
      - gleyze_network # Réseau partagé avec le Nginx reverse proxy

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    container_name: wordpress_db
    # platform: linux/x86_64  # Uncomment if your machine is running on arm (ex: Apple Silicon processor)
    ports:
      - ${IP}:${DB_PORT}:3306 # change ip if required
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - wordpressnet # db reste uniquement sur le réseau interne

volumes:
  db_data:

networks:
  wordpressnet: # Définit le réseau pour que les conteneurs communiquent
    driver: bridge
  gleyze_network: # Déclaration du réseau externe
    name: gleyze # Doit correspondre au nom du réseau utilisé par votre Nginx reverse proxy
    external: true
